import './pais.css';
import { createParentSupabase, supabaseReady, friendlyError } from '../lib/supabase.js';
import { levelOf } from '../shared/progression.js';
import { setupPWA } from '../shared/pwa.js';

const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sb=createParentSupabase();
let session=null,families=[],familyId=null,dash=null,tab='hoje',poll=null;

function toast(title,text){$('toastTitle').textContent=title;$('toastText').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function openInfo(html){$('modalBody').innerHTML=html;$('infoModal').classList.add('open')}
$('modalClose').addEventListener('click',()=>$('infoModal').classList.remove('open'));
async function rpc(fn,args={}){const {data,error}=await sb.rpc(fn,args);if(error)throw error;return data}
function isPlus(){return Boolean(dash?.family?.plus)}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}

function showAuth(){clearInterval(poll);$('authView').hidden=false;$('setupView').hidden=true;$('appView').hidden=true;$('logoutBtn').hidden=true;$('familySelect').hidden=true}
function showApp(){ $('authView').hidden=true;$('setupView').hidden=true;$('appView').hidden=false;$('logoutBtn').hidden=false;$('familySelect').hidden=families.length<2; }
function showSetup(){ $('authView').hidden=true;$('setupView').hidden=false;$('appView').hidden=true;$('logoutBtn').hidden=false;$('familySelect').hidden=true; }

$('googleLoginBtn').addEventListener('click',async()=>{
  if(!supabaseReady){$('loginError').textContent='Configure VITE_SUPABASE_URL e a publishable key no Vercel.';return}
  const btn=$('googleLoginBtn');btn.disabled=true;$('loginError').textContent='';
  try{
    const redirect=new URL('/pais/',location.origin).href;
    const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect}});
    if(error)throw error;
  }catch(err){
    $('loginError').textContent=friendlyError(err);btn.disabled=false;
  }
});
$('logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();session=null;showAuth()});

async function loadFamilies(){families=await rpc('my_families')||[];const sel=$('familySelect');sel.innerHTML=families.map((f)=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');if(!familyId||!families.some((f)=>f.id===familyId))familyId=families[0]?.id||null;if(familyId)sel.value=familyId;}
$('familySelect').addEventListener('change',async(e)=>{familyId=e.target.value;await loadDashboard()});

function setupView(){
  $('setupView').innerHTML=`<div class="setup-card"><div class="auth-hero">🏡</div><h1>Crie sua família</h1><p>Essa será a base do jogo. Depois você adiciona a criança e conecta o aparelho dela por um código.</p><form class="form" id="createFamilyForm"><label class="field">Nome da família<input class="input" name="name" maxlength="60" required placeholder="Família Almeida"></label><label class="field">Como a criança chama você?<input class="input" name="display" maxlength="30" required placeholder="Papai, Mamãe, Vó..."></label><label class="field">Seu avatar<select class="input" name="avatar"><option>🦊</option><option>🐻</option><option>🐼</option><option>🦁</option><option>🐨</option></select></label><button class="btn btn-main btn-block">Criar família</button><div class="error" id="setupError"></div></form></div>`;
  $('createFamilyForm').addEventListener('submit',async(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget),btn=e.submitter;if(btn)btn.disabled=true;try{familyId=await rpc('create_family',{p_name:fd.get('name'),p_display_name:fd.get('display'),p_avatar:fd.get('avatar')});await loadFamilies();await loadDashboard()}catch(err){$('setupError').textContent=friendlyError(err)}finally{if(btn)btn.disabled=false}});
}

async function loadDashboard(silent=false){if(!familyId)return;try{dash=await rpc('parent_dashboard',{p_family:familyId});showApp();renderHeader();render();if(!silent){clearInterval(poll);poll=setInterval(()=>loadDashboard(true),12000)}}catch(err){if(!silent)toast('Não foi possível carregar',friendlyError(err))}}
function renderHeader(){const f=dash.family;const pending=(dash.pending_missions?.length||0)+(dash.pending_rewards?.length||0);$('pendingBadge').textContent=pending?String(pending):'';$('welcome').innerHTML=`<div><h1>Olá, ${esc(dash.me?.nickname||'responsável')} 👋</h1><p>${esc(f.name)} · ${dash.today}</p></div><span class="plan-pill ${f.plus?'plus':''}">${f.plus?'Plus ✦':'Plano grátis'}</span>`;document.querySelectorAll('.parent-nav button').forEach((b)=>b.classList.toggle('active',b.dataset.tab===tab));}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
function stat(label,value){return `<div class="summary"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}

function todayView(){
  const pm=dash.pending_missions||[],pr=dash.pending_rewards||[],mine=dash.my_missions||[];
  const missionRows=pm.length?`<ul class="rows">${pm.map((x)=>`<li class="row attention"><span class="row-icon">${esc(x.icon)}</span><span class="row-main"><strong>${esc(x.nickname)} · ${esc(x.title)}</strong><small>+${x.star_reward} ⭐ · +${x.xp_reward} XP · enviado ${fmtDate(x.created_at)}</small></span><span class="row-actions"><button class="btn btn-soft" data-act="mission-reject" data-id="${x.id}">Tentar de novo</button><button class="btn btn-ok" data-act="mission-approve" data-id="${x.id}">Aprovar</button></span></li>`).join('')}</ul>`:empty('Nenhuma missão esperando aprovação.');
  const rewardRows=pr.length?`<ul class="rows">${pr.map((x)=>`<li class="row attention"><span class="row-icon">${esc(x.icon)}</span><span class="row-main"><strong>${esc(x.nickname)} pediu: ${esc(x.title)}</strong><small>${x.cost} estrelas · ${fmtDate(x.created_at)}</small></span><span class="row-actions"><button class="btn btn-soft" data-act="reward-deny" data-id="${x.id}">Agora não</button><button class="btn btn-ok" data-act="reward-deliver" data-id="${x.id}">Entregue</button></span></li>`).join('')}</ul>`:empty('Nenhum prêmio esperando decisão.');
  const mineRows=mine.length?`<ul class="rows">${mine.map((m)=>`<li class="row"><span class="row-icon">${esc(m.icon)}</span><span class="row-main"><strong>${esc(m.title)}</strong><small>+${m.star_reward} ⭐ para a meta familiar</small></span>${m.done?'<span class="badge badge-done">Feito ✓</span>':`<button class="btn btn-main" data-act="parent-done" data-id="${m.id}">Fiz</button>`}</li>`).join('')}</ul>`:empty('Sem missões de adultos ativas.');
  return `<div class="grid"><section class="card"><h2>Visão de hoje</h2><div class="summary-grid">${stat('Pendências',String(pm.length+pr.length))}${stat('Meta da família',`${dash.family_goal.current}/${dash.family_goal.target} ⭐`)}${stat('Jogadores',String(dash.players.length))}${stat('Plano',dash.family.plus?'Plus':'Grátis')}</div></section><section class="card half"><h2>Missões para confirmar</h2><p class="lead">A estrela só entra depois da sua confirmação.</p>${missionRows}</section><section class="card half"><h2>Prêmios pedidos</h2><p class="lead">O pedido já reserva as estrelas; ao negar, elas voltam.</p>${rewardRows}</section><section class="card"><h2>Suas missões</h2><p class="lead">Adultos também podem contribuir para a meta da família.</p>${mineRows}</section></div>`;
}

function familyView(){
  const players=(dash.players||[]).map((p)=>{const devs=(p.devices||[]).map((d)=>`<div class="device"><span class="status-dot"></span><small>${esc(d.label||'Aparelho')} · visto ${fmtDate(d.last_seen_at)}</small><button class="btn btn-danger" data-act="revoke-device" data-id="${d.id}">Desconectar</button></div>`).join('');return `<li class="row"><span class="row-icon">${esc(p.avatar)}</span><div class="row-main"><strong>${esc(p.nickname)} ${p.kind==='adult'?'<span class="badge badge-soft">adulto</span>':''}</strong><small>Nível ${levelOf(p.xp)} · ${p.wallet} ⭐ · sequência ${p.streak||0} dias</small>${devs}</div><span class="row-actions">${p.kind==='child'?`<button class="btn btn-main" data-act="pair-code" data-id="${p.id}">Conectar aparelho</button>`:''}</span></li>`}).join('');
  return `<div class="grid"><section class="card"><h2>Sua família</h2><p class="lead">Cada criança pode ter um aparelho conectado por um segredo local. Nenhuma conta infantil é criada no Supabase Auth.</p><ul class="rows">${players}</ul></section><section class="card half"><h2>Adicionar criança</h2><p class="lead">Plano grátis: 1 criança. Plus: até 10.</p><form class="form" data-form="create-child"><div class="two"><label class="field">Apelido<input class="input" name="nickname" maxlength="30" required></label><label class="field">Avatar<select class="input" name="avatar"><option>🌸</option><option>🦊</option><option>🐼</option><option>🦄</option><option>🐯</option><option>🐸</option></select></label></div><button class="btn btn-main">Adicionar</button></form></section><section class="card half"><h2>Como conectar</h2><p class="lead">Gere o código aqui, abra o jogo no aparelho da criança e digite o código. Ele expira em 30 minutos e só funciona uma vez.</p><button class="btn btn-soft" data-act="open-game">Abrir jogo em nova aba</button></section></div>`;
}

function missionEditor(m){return `<li class="row"><span class="row-icon">${esc(m.icon)}</span><span class="row-main"><strong>${esc(m.title)} ${m.is_custom?'<span class="badge badge-plus">personalizada</span>':''}</strong><small>${m.audience==='adult'?'Adultos':'Crianças'} · ${m.star_reward} ⭐ · ${m.xp_reward} XP · ${m.time_of_day}</small></span><span class="row-actions"><button class="btn btn-soft" data-act="edit-mission" data-id="${m.id}">Editar</button>${m.is_custom?`<button class="btn btn-danger" data-act="delete-mission" data-id="${m.id}">Excluir</button>`:''}</span></li>`}
function routineView(){const child=dash.missions.filter((m)=>m.audience==='child'),adult=dash.missions.filter((m)=>m.audience==='adult');return `<div class="grid"><section class="card"><h2>Rotina das crianças</h2><p class="lead">Estrelas alimentam recompensas; XP controla a evolução de longo prazo do personagem.</p><ul class="rows">${child.map(missionEditor).join('')}</ul><h3>Missões dos adultos</h3><ul class="rows">${adult.map(missionEditor).join('')}</ul></section><section class="card">${isPlus()?`<h2>Nova missão personalizada</h2><form class="form" data-form="create-mission"><div class="two"><label class="field">Nome<input class="input" name="title" maxlength="60" required></label><label class="field">Ícone<input class="input" name="icon" maxlength="8" value="⭐"></label></div><div class="three"><label class="field">Para<select class="input" name="audience"><option value="child">Criança</option><option value="adult">Adulto</option></select></label><label class="field">Estrelas<input class="input" type="number" name="stars" min="1" max="500" value="20"></label><label class="field">XP<input class="input" type="number" name="xp" min="0" max="250" value="10"></label></div><label class="field">Período<select class="input" name="time"><option value="any">Qualquer hora</option><option value="manha">Manhã</option><option value="tarde">Tarde</option><option value="noite">Noite</option></select></label><button class="btn btn-main">Criar missão</button></form>`:`<div class="plus-lock"><strong>Missões personalizadas são Plus ✦</strong><p class="lead">No grátis, você pode ativar/desativar e ajustar estrelas/XP das missões padrão.</p></div>`}</section></div>`}
function rewardsView(){return `<div class="grid"><section class="card"><h2>Prêmios da família</h2><p class="lead">São combinados reais. O jogo infantil não vende nada.</p><ul class="rows">${dash.rewards.map((r)=>`<li class="row"><span class="row-icon">${esc(r.icon)}</span><span class="row-main"><strong>${esc(r.title)} ${r.is_custom?'<span class="badge badge-plus">personalizado</span>':''}</strong><small>${r.cost} estrelas · ${r.active?'ativo':'desligado'}</small></span><span class="row-actions"><button class="btn btn-soft" data-act="edit-reward" data-id="${r.id}">Editar</button>${r.is_custom?`<button class="btn btn-danger" data-act="delete-reward" data-id="${r.id}">Excluir</button>`:''}</span></li>`).join('')}</ul></section><section class="card">${isPlus()?`<h2>Novo prêmio</h2><form class="form" data-form="create-reward"><div class="two"><label class="field">Nome<input class="input" name="title" maxlength="60" required></label><label class="field">Ícone<input class="input" name="icon" maxlength="8" value="🎁"></label></div><label class="field">Custo em estrelas<input class="input" type="number" name="cost" min="1" max="10000" value="100"></label><button class="btn btn-main">Criar prêmio</button></form>`:`<div class="plus-lock"><strong>Prêmios personalizados são Plus ✦</strong><p class="lead">Os prêmios padrão continuam disponíveis no plano grátis.</p></div>`}</section></div>`}
function challengesView(){const list=(dash.challenges||[]).length?`<ul class="rows">${dash.challenges.map((c)=>`<li class="row"><span class="row-icon">🎯</span><span class="row-main"><strong>${esc(c.title)}</strong><small>${c.target_days} dias · ${esc(c.mission_title)}${c.prize?` · ${esc(c.prize)}`:''}</small></span><button class="btn btn-danger" data-act="delete-challenge" data-id="${c.id}">Excluir</button></li>`).join('')}</ul>`:empty('Nenhum desafio criado.');return `<div class="grid"><section class="card"><h2>Desafios</h2>${list}</section><section class="card">${isPlus()?`<h2>Novo desafio</h2><form class="form" data-form="create-challenge"><label class="field">Título<input class="input" name="title" maxlength="60" required placeholder="7 dias lendo juntos"></label><label class="field">Missão<select class="input" name="mission">${dash.missions.filter((m)=>m.audience==='child'&&m.active).map((m)=>`<option value="${m.id}">${esc(m.icon)} ${esc(m.title)}</option>`).join('')}</select></label><div class="two"><label class="field">Meta de dias<input class="input" type="number" name="days" min="1" max="60" value="7"></label><label class="field">Para<select class="input" name="player"><option value="">Todas as crianças</option>${dash.players.filter((p)=>p.kind==='child').map((p)=>`<option value="${p.id}">${esc(p.nickname)}</option>`).join('')}</select></label></div><label class="field">Prêmio especial (opcional)<input class="input" name="prize" maxlength="80"></label><button class="btn btn-main">Criar desafio</button></form>`:`<div class="plus-lock"><strong>Desafios fazem parte do Plus ✦</strong><p class="lead">O jogo básico, missões, estrelas e recompensas continuam funcionando no plano grátis.</p></div>`}</section></div>`}
function leagueView(){const list=(dash.leagues||[]).length?dash.leagues.map((l)=>`<section class="card"><h2>${esc(l.name)}</h2><p class="lead">Código: <strong>${esc(l.code||'visível ao responsável')}</strong></p><ul class="rows">${(l.families||[]).map((f,i)=>`<li class="row"><span class="row-icon">${i+1}</span><span class="row-main"><strong>${esc(f.avatar)} ${esc(f.nickname)}</strong><small>${f.points} estrelas na semana</small></span></li>`).join('')}</ul></section>`).join(''):'';return `<div class="grid">${list||'<section class="card">'+empty('Sua família ainda não participa de uma liga.')+'</section>'}<section class="card">${isPlus()?`<h2>Criar ou entrar em uma liga</h2><div class="two"><form class="form" data-form="create-league"><label class="field">Nome da liga<input class="input" name="name" required maxlength="40"></label><label class="field">Apelido da família<input class="input" name="nickname" required maxlength="30" value="${esc(dash.family.name)}"></label><button class="btn btn-main">Criar liga</button></form><form class="form" data-form="join-league"><label class="field">Código<input class="input" name="code" required maxlength="9"></label><label class="field">Apelido da família<input class="input" name="nickname" required maxlength="30" value="${esc(dash.family.name)}"></label><button class="btn btn-soft">Entrar</button></form></div>`:`<div class="plus-lock"><strong>Ligas entre famílias são Plus ✦</strong><p class="lead">A competição é opcional; a meta cooperativa da própria família existe em todos os planos.</p></div>`}</section></div>`}
function configView(){return `<div class="grid"><section class="card half"><h2>Configurações da família</h2><form class="form" data-form="update-family"><label class="field">Nome<input class="input" name="name" maxlength="60" value="${esc(dash.family.name)}"></label><label class="field">Meta semanal de estrelas<input class="input" type="number" min="100" max="10000" step="50" name="goal" value="${dash.family.weekly_goal}"></label><button class="btn btn-main">Salvar</button></form></section><section class="card half"><h2>Plano</h2><p class="lead"><strong>${dash.family.plus?'Plus ativo':'Plano grátis'}</strong><br>${dash.family.plan_expires_at?`Válido até ${fmtDate(dash.family.plan_expires_at)}`:'Sem cobrança configurada neste ZIP.'}</p><p class="lead">Para testes, o Plus pode ser ativado manualmente pelo SQL descrito no guia.</p></section><section class="card danger-zone"><h2>Privacidade e acesso</h2><p class="lead">Crianças não têm conta de e-mail. O aparelho guarda um segredo local que pode ser revogado aqui na aba Família. Sessões dos responsáveis usam o Supabase Auth.</p><a href="/privacidade/">Política de privacidade</a> · <a href="/termos/">Termos</a></section></div>`}
function render(){if(!dash)return;renderHeader();$('view').innerHTML=tab==='hoje'?todayView():tab==='familia'?familyView():tab==='rotina'?routineView():tab==='premios'?rewardsView():tab==='desafios'?challengesView():tab==='liga'?leagueView():configView();}

document.querySelector('.parent-nav').addEventListener('click',(e)=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;render()});

async function doAction(act,id){try{
  if(act==='open-game'){window.location.assign('/');return}
  if(act==='mission-approve')await rpc('decide_mission',{p_log:id,p_approve:true});
  if(act==='mission-reject')await rpc('decide_mission',{p_log:id,p_approve:false});
  if(act==='reward-deliver')await rpc('decide_reward',{p_request:id,p_deliver:true});
  if(act==='reward-deny')await rpc('decide_reward',{p_request:id,p_deliver:false});
  if(act==='parent-done')await rpc('parent_mark_done',{p_player:dash.me.id,p_mission:id});
  if(act==='pair-code'){const x=await rpc('create_pairing_code',{p_player:id});const code=String(x.code||'');openInfo(`<h2>Conectar aparelho</h2><p>Abra o jogo no aparelho da criança e digite:</p><div class="code-box"><strong>${esc(code.slice(0,4))}-${esc(code.slice(4))}</strong><small>Válido por 30 minutos · uso único</small><button class="btn btn-main" id="copyCode">Copiar código</button></div>`);setTimeout(()=>$('copyCode')?.addEventListener('click',()=>navigator.clipboard?.writeText(code).then(()=>toast('Copiado','Código pronto para colar.'))),0);return}
  if(act==='revoke-device')await rpc('parent_revoke_device',{p_family:familyId,p_device:id});
  if(act==='delete-mission'&&confirm('Excluir esta missão personalizada?'))await rpc('parent_delete_mission',{p_family:familyId,p_mission:id});
  if(act==='delete-reward'&&confirm('Excluir este prêmio personalizado?'))await rpc('parent_delete_reward',{p_family:familyId,p_reward:id});
  if(act==='delete-challenge'&&confirm('Excluir este desafio?'))await rpc('parent_delete_challenge',{p_family:familyId,p_challenge:id});
  if(act==='edit-mission'){const m=dash.missions.find((x)=>x.id===id);openInfo(`<h2>Editar missão</h2><form class="form" id="editMission"><label class="field">Nome<input class="input" name="title" maxlength="60" value="${esc(m.title)}" ${!m.is_custom&&!isPlus()?'readonly':''}></label><div class="three"><label class="field">Ícone<input class="input" name="icon" maxlength="8" value="${esc(m.icon)}" ${!m.is_custom&&!isPlus()?'readonly':''}></label><label class="field">Estrelas<input class="input" type="number" name="stars" min="1" max="500" value="${m.star_reward}"></label><label class="field">XP<input class="input" type="number" name="xp" min="0" max="250" value="${m.xp_reward}"></label></div><label class="field">Período<select class="input" name="time"><option value="any">Qualquer hora</option><option value="manha">Manhã</option><option value="tarde">Tarde</option><option value="noite">Noite</option></select></label><label class="switch"><input type="checkbox" name="active" ${m.active?'checked':''}> Missão ativa</label><button class="btn btn-main">Salvar</button></form>`);setTimeout(()=>{const f=$('editMission');f.elements.time.value=m.time_of_day;f.addEventListener('submit',async(e)=>{e.preventDefault();const fd=new FormData(f);await rpc('parent_update_mission',{p_family:familyId,p_mission:id,p_title:fd.get('title'),p_icon:fd.get('icon'),p_star_reward:Number(fd.get('stars')),p_xp_reward:Number(fd.get('xp')),p_time_of_day:fd.get('time'),p_active:fd.get('active')==='on'});$('infoModal').classList.remove('open');await loadDashboard(true)})},0);return}
  if(act==='edit-reward'){const r=dash.rewards.find((x)=>x.id===id);openInfo(`<h2>Editar prêmio</h2><form class="form" id="editReward"><label class="field">Nome<input class="input" name="title" maxlength="60" value="${esc(r.title)}" ${!r.is_custom&&!isPlus()?'readonly':''}></label><div class="two"><label class="field">Ícone<input class="input" name="icon" maxlength="8" value="${esc(r.icon)}" ${!r.is_custom&&!isPlus()?'readonly':''}></label><label class="field">Custo<input class="input" type="number" name="cost" min="1" max="10000" value="${r.cost}"></label></div><label class="switch"><input type="checkbox" name="active" ${r.active?'checked':''}> Prêmio ativo</label><button class="btn btn-main">Salvar</button></form>`);setTimeout(()=>$('editReward').addEventListener('submit',async(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);await rpc('parent_update_reward',{p_family:familyId,p_reward:id,p_title:fd.get('title'),p_icon:fd.get('icon'),p_cost:Number(fd.get('cost')),p_active:fd.get('active')==='on'});$('infoModal').classList.remove('open');await loadDashboard(true)}),0);return}
  await loadDashboard(true);toast('Pronto','Alteração salva.');
}catch(err){toast('Ops',friendlyError(err))}}
document.addEventListener('click',(e)=>{const b=e.target.closest('[data-act]');if(b)doAction(b.dataset.act,b.dataset.id)});

document.addEventListener('submit',async(e)=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const fd=new FormData(form),name=form.dataset.form,btn=e.submitter;if(btn)btn.disabled=true;try{
  if(name==='create-child')await rpc('create_child',{p_family:familyId,p_nickname:fd.get('nickname'),p_avatar:fd.get('avatar')});
  if(name==='create-mission')await rpc('parent_create_mission',{p_family:familyId,p_title:fd.get('title'),p_icon:fd.get('icon'),p_audience:fd.get('audience'),p_star_reward:Number(fd.get('stars')),p_xp_reward:Number(fd.get('xp')),p_time_of_day:fd.get('time')});
  if(name==='create-reward')await rpc('parent_create_reward',{p_family:familyId,p_title:fd.get('title'),p_icon:fd.get('icon'),p_cost:Number(fd.get('cost'))});
  if(name==='create-challenge')await rpc('parent_create_challenge',{p_family:familyId,p_mission:fd.get('mission'),p_title:fd.get('title'),p_target_days:Number(fd.get('days')),p_prize:fd.get('prize')||null,p_player:fd.get('player')||null});
  if(name==='create-league'){const x=await rpc('create_league',{p_family:familyId,p_name:fd.get('name'),p_nickname:fd.get('nickname'),p_avatar:'🏡'});openInfo(`<h2>Liga criada</h2><p>Compartilhe este código com outra família Plus:</p><div class="code-box"><strong>${esc(x.code)}</strong></div>`)}
  if(name==='join-league')await rpc('join_league',{p_family:familyId,p_code:fd.get('code'),p_nickname:fd.get('nickname'),p_avatar:'🏡'});
  if(name==='update-family')await rpc('update_family',{p_family:familyId,p_name:fd.get('name'),p_weekly_goal:Number(fd.get('goal'))});
  form.reset();await loadDashboard(true);toast('Pronto','Alteração salva.');
}catch(err){toast('Ops',friendlyError(err))}finally{if(btn)btn.disabled=false}});

async function enterAuthenticated(){
  await loadFamilies();
  if(!families.length){showSetup();setupView();return}
  await loadDashboard();
}
async function bootstrap(){
  if(!supabaseReady){showAuth();$('loginError').textContent='Configure VITE_SUPABASE_URL e a publishable key antes de testar.';return}
  const urlError=new URLSearchParams(location.search).get('error_description')||new URLSearchParams(location.hash.slice(1)).get('error_description');
  if(urlError){showAuth();$('loginError').textContent='Não foi possível entrar com o Google. Tente novamente.';}
  const {data}=await sb.auth.getSession();session=data.session;
  if(!session){showAuth();return}
  await enterAuthenticated();
}
sb?.auth.onAuthStateChange((event,next)=>{
  const hadSession=Boolean(session);session=next;
  if(!next){showAuth();return}
  if(!hadSession||event==='SIGNED_IN')setTimeout(()=>enterAuthenticated().catch((err)=>toast('Ops',friendlyError(err))),0);
});
setupPWA();
bootstrap();
