-- ============================================================================
-- DesafIA 0.3 — instalação isolada no projeto Supabase compartilhado da minhAi
-- ============================================================================
-- IMPORTANTE:
-- * NÃO habilita Anonymous Sign-In.
-- * NÃO altera permissões, tabelas, funções ou policies do schema public.
-- * A criança usa um segredo aleatório local; apenas o SHA-256 é salvo no banco.
-- * Navegadores não recebem acesso direto às tabelas. Toda escrita/leitura passa
--   por RPCs com validação explícita.
-- * Adicione "desafia" aos Exposed schemas da Data API após executar este SQL.
-- ============================================================================

begin;

create schema if not exists desafia;
comment on schema desafia is 'DesafIA — jogo familiar de hábitos da BigCorps.';

-- --------------------------------------------------------------------------
-- Tabelas
-- --------------------------------------------------------------------------
create table if not exists desafia.families (
  id              uuid primary key default gen_random_uuid(),
  name            text not null check (char_length(name) between 1 and 60),
  plan            text not null default 'free' check (plan in ('free','plus')),
  plan_expires_at timestamptz,
  timezone        text not null default 'America/Sao_Paulo',
  weekly_goal     integer not null default 500 check (weekly_goal between 100 and 10000),
  created_at      timestamptz not null default now()
);

create table if not exists desafia.family_members (
  family_id    uuid not null references desafia.families(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  role         text not null default 'parent' check (role in ('owner','parent')),
  display_name text not null default 'Responsável' check (char_length(display_name) between 1 and 30),
  created_at   timestamptz not null default now(),
  primary key (family_id,user_id)
);
create index if not exists desafia_family_members_user_idx on desafia.family_members(user_id);

create table if not exists desafia.players (
  id         uuid primary key default gen_random_uuid(),
  family_id  uuid not null references desafia.families(id) on delete cascade,
  kind       text not null default 'child' check (kind in ('child','adult')),
  user_id    uuid references auth.users(id) on delete cascade,
  nickname   text not null check (char_length(nickname) between 1 and 30),
  avatar     text not null default '🌸' check (char_length(avatar) <= 16),
  pet_name   text not null default 'Pipo' check (char_length(pet_name) between 1 and 12),
  look       jsonb not null default '{"color":"rosa","hat":"none","acc":"none"}'::jsonb,
  xp         integer not null default 0 check (xp >= 0),
  wallet     integer not null default 0 check (wallet >= 0),
  created_at timestamptz not null default now(),
  unique (family_id,user_id),
  check ((kind='adult') = (user_id is not null))
);
create index if not exists desafia_players_family_idx on desafia.players(family_id);

-- O segredo do aparelho NUNCA é salvo em texto. token_hash = SHA-256 do segredo.
create table if not exists desafia.devices (
  id           uuid primary key default gen_random_uuid(),
  player_id    uuid not null references desafia.players(id) on delete cascade,
  token_hash   bytea not null unique,
  label        text not null default 'Aparelho' check (char_length(label) between 1 and 40),
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at   timestamptz
);
create index if not exists desafia_devices_player_idx on desafia.devices(player_id);

create table if not exists desafia.pairing_codes (
  code       text primary key,
  player_id  uuid not null references desafia.players(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists desafia_pairing_codes_exp_idx on desafia.pairing_codes(expires_at);

-- Limite leve por segredo local. O código em si tem ~40 bits de entropia.
create table if not exists desafia.pairing_attempts (
  id         bigint generated by default as identity primary key,
  token_hash bytea not null,
  attempted_at timestamptz not null default now(),
  success    boolean not null default false
);
create index if not exists desafia_pairing_attempts_hash_time_idx on desafia.pairing_attempts(token_hash,attempted_at desc);

create table if not exists desafia.parent_invites (
  code       text primary key,
  family_id  uuid not null references desafia.families(id) on delete cascade,
  expires_at timestamptz not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists desafia.missions (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references desafia.families(id) on delete cascade,
  audience    text not null default 'child' check (audience in ('child','adult')),
  title       text not null check (char_length(title) between 1 and 60),
  icon        text not null default '⭐' check (char_length(icon) <= 16),
  star_reward integer not null default 20 check (star_reward between 1 and 500),
  xp_reward   integer not null default 10 check (xp_reward between 0 and 250),
  time_of_day text not null default 'any' check (time_of_day in ('any','manha','tarde','noite')),
  active      boolean not null default true,
  is_custom   boolean not null default false,
  sort        integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists desafia_missions_family_idx on desafia.missions(family_id);

create table if not exists desafia.mission_logs (
  id          uuid primary key default gen_random_uuid(),
  player_id   uuid not null references desafia.players(id) on delete cascade,
  mission_id  uuid not null references desafia.missions(id) on delete cascade,
  day         date not null,
  status      text not null default 'pending' check (status in ('pending','done','rejected')),
  star_reward integer not null check (star_reward > 0),
  xp_reward   integer not null check (xp_reward >= 0),
  created_at  timestamptz not null default now(),
  decided_at  timestamptz,
  decided_by  uuid references auth.users(id) on delete set null,
  unique (player_id,mission_id,day)
);
create index if not exists desafia_mission_logs_player_day_idx on desafia.mission_logs(player_id,day);

create table if not exists desafia.daily_completions (
  player_id  uuid not null references desafia.players(id) on delete cascade,
  day        date not null,
  star_bonus integer not null default 25 check (star_bonus >= 0),
  xp_bonus   integer not null default 15 check (xp_bonus >= 0),
  created_at timestamptz not null default now(),
  primary key (player_id,day)
);

create table if not exists desafia.rewards (
  id         uuid primary key default gen_random_uuid(),
  family_id  uuid not null references desafia.families(id) on delete cascade,
  title      text not null check (char_length(title) between 1 and 60),
  icon       text not null default '🎁' check (char_length(icon) <= 16),
  cost       integer not null check (cost between 1 and 10000),
  active     boolean not null default true,
  is_custom  boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists desafia_rewards_family_idx on desafia.rewards(family_id);

create table if not exists desafia.reward_requests (
  id         uuid primary key default gen_random_uuid(),
  player_id  uuid not null references desafia.players(id) on delete cascade,
  reward_id  uuid not null references desafia.rewards(id) on delete cascade,
  cost       integer not null check (cost > 0),
  status     text not null default 'pending' check (status in ('pending','delivered','denied')),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references auth.users(id) on delete set null
);
create unique index if not exists desafia_reward_requests_one_pending
  on desafia.reward_requests(player_id,reward_id) where status='pending';

create table if not exists desafia.challenges (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references desafia.families(id) on delete cascade,
  player_id   uuid references desafia.players(id) on delete cascade,
  mission_id  uuid not null references desafia.missions(id) on delete cascade,
  title       text not null check (char_length(title) between 1 and 60),
  target_days integer not null check (target_days between 1 and 60),
  prize       text check (char_length(prize) <= 80),
  starts_on   date not null,
  ends_on     date not null,
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  check (ends_on >= starts_on)
);
create index if not exists desafia_challenges_family_idx on desafia.challenges(family_id);

create table if not exists desafia.leagues (
  id           uuid primary key default gen_random_uuid(),
  name         text not null check (char_length(name) between 1 and 40),
  code         text not null unique,
  owner_family uuid not null references desafia.families(id) on delete cascade,
  created_at   timestamptz not null default now()
);
create table if not exists desafia.league_families (
  league_id uuid not null references desafia.leagues(id) on delete cascade,
  family_id uuid not null references desafia.families(id) on delete cascade,
  nickname  text not null check (char_length(nickname) between 1 and 30),
  avatar    text not null default '🏡' check (char_length(avatar) <= 16),
  joined_at timestamptz not null default now(),
  primary key (league_id,family_id)
);

-- --------------------------------------------------------------------------
-- Defesa em profundidade: RLS ativa em TODAS as tabelas. O browser não ganha
-- privilégios diretos; portanto nenhuma policy permissiva é necessária.
-- --------------------------------------------------------------------------
alter table desafia.families enable row level security;
alter table desafia.family_members enable row level security;
alter table desafia.players enable row level security;
alter table desafia.devices enable row level security;
alter table desafia.pairing_codes enable row level security;
alter table desafia.pairing_attempts enable row level security;
alter table desafia.parent_invites enable row level security;
alter table desafia.missions enable row level security;
alter table desafia.mission_logs enable row level security;
alter table desafia.daily_completions enable row level security;
alter table desafia.rewards enable row level security;
alter table desafia.reward_requests enable row level security;
alter table desafia.challenges enable row level security;
alter table desafia.leagues enable row level security;
alter table desafia.league_families enable row level security;

-- --------------------------------------------------------------------------
-- Helpers internos
-- --------------------------------------------------------------------------
create or replace function desafia.real_user()
returns boolean language sql stable
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select auth.uid() is not null
     and not coalesce((auth.jwt()->>'is_anonymous')::boolean,false)
$$;

create or replace function desafia.is_family_parent(fid uuid)
returns boolean language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select desafia.real_user() and exists (
    select 1 from desafia.family_members m
    where m.family_id=fid and m.user_id=auth.uid()
  )
$$;

create or replace function desafia.family_is_plus(fid uuid)
returns boolean language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select exists (
    select 1 from desafia.families f
    where f.id=fid and f.plan='plus'
      and (f.plan_expires_at is null or f.plan_expires_at>now())
  )
$$;

create or replace function desafia.family_today(fid uuid)
returns date language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select (now() at time zone coalesce((select timezone from desafia.families where id=fid),'America/Sao_Paulo'))::date
$$;

create or replace function desafia.family_week_start(fid uuid)
returns date language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select date_trunc('week',desafia.family_today(fid)::timestamp)::date
$$;

create or replace function desafia.clean_code(raw text)
returns text language sql immutable
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select upper(regexp_replace(coalesce(raw,''),'[^A-Za-z0-9]','','g'))
$$;

create or replace function desafia.new_code()
returns text language plpgsql volatile security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  raw bytea := extensions.gen_random_bytes(8);
  result text := '';
  i int;
begin
  for i in 0..7 loop
    result := result || substr(alphabet,(get_byte(raw,i) % length(alphabet))+1,1);
  end loop;
  return result;
end $$;

create or replace function desafia.token_hash(p_token text)
returns bytea language plpgsql immutable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if p_token is null or p_token !~ '^[A-Za-z0-9_-]{40,80}$' then
    raise exception 'INVALID_DEVICE_TOKEN';
  end if;
  return extensions.digest(p_token,'sha256');
end $$;

create or replace function desafia.device_player(p_token text)
returns uuid language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select d.player_id from desafia.devices d
  where d.token_hash=desafia.token_hash(p_token) and d.revoked_at is null
$$;

create or replace function desafia.player_week_points(pid uuid, since_day date)
returns integer language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select (
    coalesce((select sum(l.star_reward) from desafia.mission_logs l
      where l.player_id=pid and l.status='done' and l.day>=since_day),0)
    + coalesce((select sum(d.star_bonus) from desafia.daily_completions d
      where d.player_id=pid and d.day>=since_day),0)
  )::int
$$;

create or replace function desafia.family_week_points(fid uuid)
returns integer language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select coalesce(sum(desafia.player_week_points(p.id,desafia.family_week_start(fid))),0)::int
  from desafia.players p where p.family_id=fid
$$;

create or replace function desafia.player_streak(pid uuid, fid uuid)
returns integer language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  with recursive latest as (
    select max(day) as day from desafia.daily_completions
    where player_id=pid and day>=desafia.family_today(fid)-1
  ), streak(day,n) as (
    select day,1 from latest where day is not null
    union all
    select d.day,s.n+1
    from streak s join desafia.daily_completions d
      on d.player_id=pid and d.day=s.day-1
  )
  select coalesce(max(n),0)::int from streak
$$;

create or replace function desafia.challenge_progress(cid uuid, pid uuid)
returns integer language sql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
  select count(distinct l.day)::int
  from desafia.challenges c
  join desafia.mission_logs l on l.mission_id=c.mission_id and l.player_id=pid
  where c.id=cid and l.status='done' and l.day between c.starts_on and c.ends_on
$$;

create or replace function desafia.seed_family(fid uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  insert into desafia.missions(family_id,audience,title,icon,star_reward,xp_reward,time_of_day,sort) values
    (fid,'child','Escovar os dentes','🪥',20,10,'any',1),
    (fid,'child','Arrumar a cama','🛏️',20,10,'manha',2),
    (fid,'child','Ler por 10 minutos','📚',20,10,'any',3),
    (fid,'child','Beber um copo de água','💧',10,5,'any',4),
    (fid,'child','Guardar os brinquedos','🧸',20,10,'noite',5),
    (fid,'child','Fazer a lição de casa','✏️',30,18,'tarde',6),
    (fid,'adult','Ler junto com as crianças','📖',20,8,'any',1),
    (fid,'adult','Jantar sem celular','📵',20,8,'noite',2),
    (fid,'adult','Brincar 20 minutos','🧩',20,8,'any',3);
  insert into desafia.rewards(family_id,title,icon,cost) values
    (fid,'Escolher o jantar','🍕',40),
    (fid,'Sorvete com a família','🍦',60),
    (fid,'Noite de filme','🎬',80),
    (fid,'Tarde no parque','🛝',120),
    (fid,'Passeio especial','🏝️',200);
end $$;

create or replace function desafia.maybe_award_daily_bonus(pid uuid)
returns boolean language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare
  p desafia.players;
  today date;
  expected_count int;
  done_count int;
  inserted_count int;
begin
  select * into p from desafia.players where id=pid;
  if p.id is null or p.kind<>'child' then return false; end if;
  today:=desafia.family_today(p.family_id);
  select count(*) into expected_count from desafia.missions m
    where m.family_id=p.family_id and m.audience='child' and m.active;
  if expected_count=0 then return false; end if;
  select count(*) into done_count from desafia.mission_logs l
    join desafia.missions m on m.id=l.mission_id
    where l.player_id=pid and l.day=today and l.status='done'
      and m.family_id=p.family_id and m.audience='child' and m.active;
  if done_count<expected_count then return false; end if;
  insert into desafia.daily_completions(player_id,day,star_bonus,xp_bonus)
    values(pid,today,25,15) on conflict do nothing;
  get diagnostics inserted_count=row_count;
  if inserted_count>0 then
    update desafia.players set wallet=wallet+25,xp=xp+15 where id=pid;
    return true;
  end if;
  return false;
end $$;

-- --------------------------------------------------------------------------
-- RPCs de responsáveis (Supabase Auth normal)
-- --------------------------------------------------------------------------
create or replace function desafia.my_families()
returns jsonb language plpgsql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.real_user() then raise exception 'LOGIN_REQUIRED'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'id',f.id,'name',f.name,'role',m.role,'created_at',f.created_at
  ) order by f.created_at)
  from desafia.family_members m join desafia.families f on f.id=m.family_id
  where m.user_id=auth.uid()),'[]'::jsonb);
end $$;

create or replace function desafia.create_family(p_name text,p_display_name text,p_avatar text default '🦊')
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare fid uuid;
begin
  if not desafia.real_user() then raise exception 'LOGIN_REQUIRED'; end if;
  if char_length(trim(p_name)) not between 1 and 60 then raise exception 'INVALID_NAME'; end if;
  insert into desafia.families(name) values(trim(p_name)) returning id into fid;
  insert into desafia.family_members(family_id,user_id,role,display_name)
    values(fid,auth.uid(),'owner',left(coalesce(nullif(trim(p_display_name),''),'Responsável'),30));
  insert into desafia.players(family_id,kind,user_id,nickname,avatar)
    values(fid,'adult',auth.uid(),left(coalesce(nullif(trim(p_display_name),''),'Responsável'),30),coalesce(nullif(p_avatar,''),'🦊'));
  perform desafia.seed_family(fid);
  return fid;
end $$;

create or replace function desafia.update_family(p_family uuid,p_name text,p_weekly_goal integer)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  update desafia.families set
    name=left(coalesce(nullif(trim(p_name),''),name),60),
    weekly_goal=greatest(100,least(10000,coalesce(p_weekly_goal,weekly_goal)))
  where id=p_family;
end $$;

create or replace function desafia.create_child(p_family uuid,p_nickname text,p_avatar text default '🌸')
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare pid uuid;n int;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  perform 1 from desafia.families where id=p_family for update;
  select count(*) into n from desafia.players where family_id=p_family and kind='child';
  if n>=1 and not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  if n>=10 then raise exception 'LIMIT_REACHED'; end if;
  insert into desafia.players(family_id,kind,nickname,avatar)
    values(p_family,'child',left(trim(p_nickname),30),coalesce(nullif(p_avatar,''),'🌸')) returning id into pid;
  return pid;
end $$;

create or replace function desafia.update_player(p_family uuid,p_player uuid,p_nickname text,p_avatar text)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  update desafia.players set nickname=left(coalesce(nullif(trim(p_nickname),''),nickname),30),avatar=coalesce(nullif(p_avatar,''),avatar)
  where id=p_player and family_id=p_family;
end $$;

create or replace function desafia.create_pairing_code(p_player uuid)
returns jsonb language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare fid uuid;c text;exp timestamptz:=now()+interval '30 minutes';
begin
  select family_id into fid from desafia.players where id=p_player and kind='child';
  if fid is null or not desafia.is_family_parent(fid) then raise exception 'FORBIDDEN'; end if;
  delete from desafia.pairing_codes where player_id=p_player or expires_at<now();
  loop
    c:=desafia.new_code();
    begin
      insert into desafia.pairing_codes(code,player_id,expires_at) values(c,p_player,exp);exit;
    exception when unique_violation then null;
    end;
  end loop;
  return jsonb_build_object('code',c,'expires_at',exp);
end $$;

create or replace function desafia.parent_revoke_device(p_family uuid,p_device uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  update desafia.devices d set revoked_at=now()
  from desafia.players p where d.id=p_device and d.player_id=p.id and p.family_id=p_family;
end $$;

create or replace function desafia.create_parent_invite(p_family uuid)
returns jsonb language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare c text;exp timestamptz:=now()+interval '2 days';
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  delete from desafia.parent_invites where expires_at<now();
  loop
    c:=desafia.new_code();
    begin
      insert into desafia.parent_invites(code,family_id,expires_at,created_by)
        values(c,p_family,exp,auth.uid());
      exit;
    exception when unique_violation then
      null;
    end;
  end loop;
  return jsonb_build_object('code',c,'expires_at',exp);
end $$;

create or replace function desafia.accept_parent_invite(p_code text,p_display_name text,p_avatar text default '🐻')
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare fid uuid;
begin
  if not desafia.real_user() then raise exception 'LOGIN_REQUIRED'; end if;
  select family_id into fid from desafia.parent_invites where code=desafia.clean_code(p_code) and expires_at>now() for update;
  if fid is null then raise exception 'INVALID_CODE'; end if;
  insert into desafia.family_members(family_id,user_id,role,display_name)
    values(fid,auth.uid(),'parent',left(trim(p_display_name),30)) on conflict(family_id,user_id) do nothing;
  insert into desafia.players(family_id,kind,user_id,nickname,avatar)
    values(fid,'adult',auth.uid(),left(trim(p_display_name),30),coalesce(nullif(p_avatar,''),'🐻')) on conflict(family_id,user_id) do nothing;
  delete from desafia.parent_invites where code=desafia.clean_code(p_code);
  return fid;
end $$;

create or replace function desafia.decide_mission(p_log uuid,p_approve boolean)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare l desafia.mission_logs;fid uuid;
begin
  select ml.* into l from desafia.mission_logs ml where ml.id=p_log for update;
  select p.family_id into fid from desafia.players p where p.id=l.player_id;
  if l.id is null or not desafia.is_family_parent(fid) then raise exception 'FORBIDDEN'; end if;
  if l.status<>'pending' then return; end if;
  update desafia.mission_logs set status=case when p_approve then 'done' else 'rejected' end,decided_at=now(),decided_by=auth.uid() where id=p_log;
  if p_approve then
    update desafia.players set xp=xp+l.xp_reward,wallet=wallet+l.star_reward where id=l.player_id;
    perform desafia.maybe_award_daily_bonus(l.player_id);
  end if;
end $$;

create or replace function desafia.parent_mark_done(p_player uuid,p_mission uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare p desafia.players;m desafia.missions;today date;changed int;
begin
  select * into p from desafia.players where id=p_player;
  if p.id is null or not desafia.is_family_parent(p.family_id) then raise exception 'FORBIDDEN'; end if;
  if p.kind='adult' and p.user_id<>auth.uid() then raise exception 'FORBIDDEN'; end if;
  select * into m from desafia.missions where id=p_mission and family_id=p.family_id and active;
  if m.id is null or (m.audience='adult')<>(p.kind='adult') then raise exception 'INVALID_MISSION'; end if;
  today:=desafia.family_today(p.family_id);
  insert into desafia.mission_logs(player_id,mission_id,day,status,star_reward,xp_reward,decided_at,decided_by)
    values(p.id,m.id,today,'done',m.star_reward,m.xp_reward,now(),auth.uid())
  on conflict(player_id,mission_id,day) do update
    set status='done',star_reward=excluded.star_reward,xp_reward=excluded.xp_reward,decided_at=now(),decided_by=auth.uid()
    where desafia.mission_logs.status<>'done';
  get diagnostics changed=row_count;
  if changed=0 then return; end if;
  update desafia.players set xp=xp+m.xp_reward,wallet=wallet+m.star_reward where id=p.id;
  perform desafia.maybe_award_daily_bonus(p.id);
end $$;

create or replace function desafia.decide_reward(p_request uuid,p_deliver boolean)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare r desafia.reward_requests;fid uuid;
begin
  select q.* into r from desafia.reward_requests q where q.id=p_request for update;
  select p.family_id into fid from desafia.players p where p.id=r.player_id;
  if r.id is null or not desafia.is_family_parent(fid) then raise exception 'FORBIDDEN'; end if;
  if r.status<>'pending' then return; end if;
  update desafia.reward_requests set status=case when p_deliver then 'delivered' else 'denied' end,decided_at=now(),decided_by=auth.uid() where id=p_request;
  if not p_deliver then update desafia.players set wallet=wallet+r.cost where id=r.player_id; end if;
end $$;

create or replace function desafia.parent_update_mission(
  p_family uuid,p_mission uuid,p_title text,p_icon text,p_star_reward integer,p_xp_reward integer,p_time_of_day text,p_active boolean
) returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare old desafia.missions;plus boolean;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  select * into old from desafia.missions where id=p_mission and family_id=p_family;
  if old.id is null then raise exception 'INVALID_MISSION'; end if;
  plus:=desafia.family_is_plus(p_family);
  if old.is_custom and not plus and (
    trim(p_title) is distinct from old.title or p_icon is distinct from old.icon or p_star_reward is distinct from old.star_reward or p_xp_reward is distinct from old.xp_reward or p_time_of_day is distinct from old.time_of_day
  ) then raise exception 'PLUS_REQUIRED'; end if;
  update desafia.missions set
    title=case when old.is_custom or plus then left(coalesce(nullif(trim(p_title),''),old.title),60) else old.title end,
    icon=case when old.is_custom or plus then coalesce(nullif(p_icon,''),old.icon) else old.icon end,
    star_reward=greatest(1,least(500,coalesce(p_star_reward,old.star_reward))),
    xp_reward=greatest(0,least(250,coalesce(p_xp_reward,old.xp_reward))),
    time_of_day=case when p_time_of_day in('any','manha','tarde','noite') then p_time_of_day else old.time_of_day end,
    active=coalesce(p_active,old.active)
  where id=old.id;
end $$;

create or replace function desafia.parent_create_mission(
  p_family uuid,p_title text,p_icon text,p_audience text,p_star_reward integer,p_xp_reward integer,p_time_of_day text
) returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare mid uuid;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  if not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  if p_audience not in('child','adult') or p_time_of_day not in('any','manha','tarde','noite') then raise exception 'INVALID_MISSION'; end if;
  insert into desafia.missions(family_id,audience,title,icon,star_reward,xp_reward,time_of_day,active,is_custom,sort)
    values(p_family,p_audience,left(trim(p_title),60),coalesce(nullif(p_icon,''),'⭐'),greatest(1,least(500,p_star_reward)),greatest(0,least(250,p_xp_reward)),p_time_of_day,true,true,999)
    returning id into mid;
  return mid;
end $$;

create or replace function desafia.parent_delete_mission(p_family uuid,p_mission uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  delete from desafia.missions where id=p_mission and family_id=p_family and is_custom;
end $$;

create or replace function desafia.parent_update_reward(p_family uuid,p_reward uuid,p_title text,p_icon text,p_cost integer,p_active boolean)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare old desafia.rewards;plus boolean;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  select * into old from desafia.rewards where id=p_reward and family_id=p_family;
  if old.id is null then raise exception 'INVALID_REWARD'; end if;
  plus:=desafia.family_is_plus(p_family);
  if old.is_custom and not plus and (trim(p_title) is distinct from old.title or p_icon is distinct from old.icon or p_cost is distinct from old.cost) then raise exception 'PLUS_REQUIRED'; end if;
  update desafia.rewards set
    title=case when old.is_custom or plus then left(coalesce(nullif(trim(p_title),''),old.title),60) else old.title end,
    icon=case when old.is_custom or plus then coalesce(nullif(p_icon,''),old.icon) else old.icon end,
    cost=greatest(1,least(10000,coalesce(p_cost,old.cost))),active=coalesce(p_active,old.active)
  where id=old.id;
end $$;

create or replace function desafia.parent_create_reward(p_family uuid,p_title text,p_icon text,p_cost integer)
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare rid uuid;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  if not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  insert into desafia.rewards(family_id,title,icon,cost,active,is_custom)
    values(p_family,left(trim(p_title),60),coalesce(nullif(p_icon,''),'🎁'),greatest(1,least(10000,p_cost)),true,true) returning id into rid;
  return rid;
end $$;

create or replace function desafia.parent_delete_reward(p_family uuid,p_reward uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  delete from desafia.rewards where id=p_reward and family_id=p_family and is_custom;
end $$;

create or replace function desafia.parent_create_challenge(p_family uuid,p_mission uuid,p_title text,p_target_days integer,p_prize text default null,p_player uuid default null)
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare cid uuid;today date;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  if not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  if not exists(select 1 from desafia.missions where id=p_mission and family_id=p_family and audience='child') then raise exception 'INVALID_MISSION'; end if;
  if p_player is not null and not exists(select 1 from desafia.players where id=p_player and family_id=p_family and kind='child') then raise exception 'FORBIDDEN'; end if;
  today:=desafia.family_today(p_family);
  insert into desafia.challenges(family_id,player_id,mission_id,title,target_days,prize,starts_on,ends_on,created_by)
    values(p_family,p_player,p_mission,left(trim(p_title),60),greatest(1,least(60,p_target_days)),nullif(left(coalesce(p_prize,''),80),''),today,today+greatest(1,least(60,p_target_days))-1,auth.uid()) returning id into cid;
  return cid;
end $$;

create or replace function desafia.parent_delete_challenge(p_family uuid,p_challenge uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  delete from desafia.challenges where id=p_challenge and family_id=p_family;
end $$;

create or replace function desafia.create_league(p_family uuid,p_name text,p_nickname text,p_avatar text default '🏡')
returns jsonb language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare lid uuid;c text;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  if not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  loop
    c:=desafia.new_code();
    begin
      insert into desafia.leagues(name,code,owner_family)
        values(left(trim(p_name),40),c,p_family)
        returning id into lid;
      exit;
    exception when unique_violation then
      null;
    end;
  end loop;
  insert into desafia.league_families(league_id,family_id,nickname,avatar) values(lid,p_family,left(trim(p_nickname),30),coalesce(nullif(p_avatar,''),'🏡'));
  return jsonb_build_object('id',lid,'code',c);
end $$;

create or replace function desafia.join_league(p_family uuid,p_code text,p_nickname text,p_avatar text default '🏡')
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare lid uuid;n int;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  if not desafia.family_is_plus(p_family) then raise exception 'PLUS_REQUIRED'; end if;
  select id into lid from desafia.leagues where code=desafia.clean_code(p_code) for update;
  if lid is null then raise exception 'INVALID_CODE'; end if;
  select count(*) into n from desafia.league_families where league_id=lid;
  if n>=20 then raise exception 'LIMIT_REACHED'; end if;
  insert into desafia.league_families(league_id,family_id,nickname,avatar)
    values(lid,p_family,left(trim(p_nickname),30),coalesce(nullif(p_avatar,''),'🏡'))
  on conflict(league_id,family_id) do update set nickname=excluded.nickname,avatar=excluded.avatar;
  return lid;
end $$;

create or replace function desafia.league_scores(p_league uuid,p_family uuid)
returns jsonb language plpgsql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if not exists(select 1 from desafia.league_families where league_id=p_league and family_id=p_family) then raise exception 'FORBIDDEN'; end if;
  return (select jsonb_build_object(
    'id',l.id,'name',l.name,'code',case when desafia.is_family_parent(p_family) then l.code end,
    'families',coalesce((select jsonb_agg(jsonb_build_object('nickname',lf.nickname,'avatar',lf.avatar,'points',desafia.family_week_points(lf.family_id),'mine',lf.family_id=p_family) order by desafia.family_week_points(lf.family_id) desc) from desafia.league_families lf where lf.league_id=l.id),'[]'::jsonb)
  ) from desafia.leagues l where l.id=p_league);
end $$;

create or replace function desafia.parent_dashboard(p_family uuid)
returns jsonb language plpgsql stable security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare ws date;today date;
begin
  if not desafia.is_family_parent(p_family) then raise exception 'FORBIDDEN'; end if;
  today:=desafia.family_today(p_family);ws:=desafia.family_week_start(p_family);
  return jsonb_build_object(
    'family',(select jsonb_build_object('id',f.id,'name',f.name,'plan',f.plan,'plus',desafia.family_is_plus(f.id),'plan_expires_at',f.plan_expires_at,'timezone',f.timezone,'weekly_goal',f.weekly_goal,'is_owner',exists(select 1 from desafia.family_members fm where fm.family_id=f.id and fm.user_id=auth.uid() and fm.role='owner')) from desafia.families f where f.id=p_family),
    'today',today,'week_start',ws,
    'family_goal',jsonb_build_object('current',desafia.family_week_points(p_family),'target',(select weekly_goal from desafia.families where id=p_family)),
    'me',(select jsonb_build_object('id',p.id,'nickname',p.nickname,'avatar',p.avatar) from desafia.players p where p.family_id=p_family and p.user_id=auth.uid()),
    'players',coalesce((select jsonb_agg(jsonb_build_object(
      'id',p.id,'kind',p.kind,'nickname',p.nickname,'avatar',p.avatar,'pet_name',p.pet_name,'look',p.look,'xp',p.xp,'wallet',p.wallet,
      'week_points',desafia.player_week_points(p.id,ws),'streak',desafia.player_streak(p.id,p_family),
      'devices',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'label',d.label,'created_at',d.created_at,'last_seen_at',d.last_seen_at) order by d.created_at) from desafia.devices d where d.player_id=p.id and d.revoked_at is null),'[]'::jsonb)
    ) order by p.kind desc,p.created_at) from desafia.players p where p.family_id=p_family),'[]'::jsonb),
    'pending_missions',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'player_id',p.id,'nickname',p.nickname,'avatar',p.avatar,'title',m.title,'icon',m.icon,'star_reward',l.star_reward,'xp_reward',l.xp_reward,'day',l.day,'created_at',l.created_at) order by l.created_at) from desafia.mission_logs l join desafia.players p on p.id=l.player_id join desafia.missions m on m.id=l.mission_id where p.family_id=p_family and l.status='pending'),'[]'::jsonb),
    'pending_rewards',coalesce((select jsonb_agg(jsonb_build_object('id',q.id,'player_id',p.id,'nickname',p.nickname,'avatar',p.avatar,'title',r.title,'icon',r.icon,'cost',q.cost,'created_at',q.created_at) order by q.created_at) from desafia.reward_requests q join desafia.players p on p.id=q.player_id join desafia.rewards r on r.id=q.reward_id where p.family_id=p_family and q.status='pending'),'[]'::jsonb),
    'missions',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'audience',m.audience,'title',m.title,'icon',m.icon,'star_reward',m.star_reward,'xp_reward',m.xp_reward,'time_of_day',m.time_of_day,'active',m.active,'is_custom',m.is_custom,'sort',m.sort) order by m.audience,m.sort,m.created_at) from desafia.missions m where m.family_id=p_family),'[]'::jsonb),
    'rewards',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'title',r.title,'icon',r.icon,'cost',r.cost,'active',r.active,'is_custom',r.is_custom) order by r.cost) from desafia.rewards r where r.family_id=p_family),'[]'::jsonb),
    'my_missions',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'title',m.title,'icon',m.icon,'star_reward',m.star_reward,'xp_reward',m.xp_reward,'done',exists(select 1 from desafia.mission_logs l where l.player_id=p.id and l.mission_id=m.id and l.day=today and l.status='done')) order by m.sort) from desafia.players p join desafia.missions m on m.family_id=p.family_id and m.audience='adult' and m.active where p.family_id=p_family and p.user_id=auth.uid()),'[]'::jsonb),
    'challenges',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'title',c.title,'target_days',c.target_days,'prize',c.prize,'starts_on',c.starts_on,'ends_on',c.ends_on,'player_id',c.player_id,'mission_title',m.title,'mission_icon',m.icon,'progress',coalesce((select jsonb_agg(jsonb_build_object('nickname',p.nickname,'avatar',p.avatar,'done',desafia.challenge_progress(c.id,p.id)) order by p.created_at) from desafia.players p where p.family_id=p_family and p.kind='child' and (c.player_id is null or c.player_id=p.id)),'[]'::jsonb)) order by c.ends_on desc) from desafia.challenges c join desafia.missions m on m.id=c.mission_id where c.family_id=p_family and c.ends_on>=today-14),'[]'::jsonb),
    'leagues',coalesce((select jsonb_agg(desafia.league_scores(lf.league_id,p_family)) from desafia.league_families lf where lf.family_id=p_family),'[]'::jsonb)
  );
end $$;

-- --------------------------------------------------------------------------
-- RPCs do aparelho infantil — SEM Supabase Auth
-- --------------------------------------------------------------------------
create or replace function desafia.pair_device(p_code text,p_device_token text,p_label text default 'Aparelho')
returns uuid language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare h bytea;pid uuid;fail_count int;did uuid;
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  h:=desafia.token_hash(p_device_token);
  select count(*) into fail_count from desafia.pairing_attempts where token_hash=h and not success and attempted_at>now()-interval '10 minutes';
  if fail_count>=12 then raise exception 'TOO_MANY_ATTEMPTS'; end if;
  select player_id into pid from desafia.pairing_codes where code=desafia.clean_code(p_code) and expires_at>now() for update;
  if pid is null then
    insert into desafia.pairing_attempts(token_hash,success) values(h,false);
    raise exception 'INVALID_CODE';
  end if;
  if not exists(select 1 from desafia.players where id=pid and kind='child') then raise exception 'CHILD_ONLY'; end if;
  insert into desafia.devices(player_id,token_hash,label,revoked_at,last_seen_at)
    values(pid,h,left(coalesce(nullif(trim(p_label),''),'Aparelho'),40),null,now())
  on conflict(token_hash) do update set player_id=excluded.player_id,label=excluded.label,revoked_at=null,last_seen_at=now()
  returning id into did;
  insert into desafia.pairing_attempts(token_hash,success) values(h,true);
  delete from desafia.pairing_codes where player_id=pid;
  return pid;
end $$;

create or replace function desafia.unpair_device(p_device_token text)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  update desafia.devices set revoked_at=now() where token_hash=desafia.token_hash(p_device_token) and revoked_at is null;
end $$;

create or replace function desafia.mark_mission_done(p_device_token text,p_mission uuid)
returns text language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare pid uuid;p desafia.players;m desafia.missions;today date;st text;
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  pid:=desafia.device_player(p_device_token);if pid is null then raise exception 'NOT_PAIRED'; end if;
  select * into p from desafia.players where id=pid;
  select * into m from desafia.missions where id=p_mission and family_id=p.family_id and active and audience='child';
  if m.id is null then raise exception 'INVALID_MISSION'; end if;
  today:=desafia.family_today(p.family_id);
  insert into desafia.mission_logs(player_id,mission_id,day,status,star_reward,xp_reward)
    values(pid,m.id,today,'pending',m.star_reward,m.xp_reward)
  on conflict(player_id,mission_id,day) do update set status='pending',created_at=now(),decided_at=null,decided_by=null,star_reward=excluded.star_reward,xp_reward=excluded.xp_reward where desafia.mission_logs.status='rejected';
  select status into st from desafia.mission_logs where player_id=pid and mission_id=m.id and day=today;
  update desafia.devices set last_seen_at=now() where token_hash=desafia.token_hash(p_device_token);
  return st;
end $$;

create or replace function desafia.request_reward(p_device_token text,p_reward uuid)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare pid uuid;p desafia.players;r desafia.rewards;changed int;
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  pid:=desafia.device_player(p_device_token);if pid is null then raise exception 'NOT_PAIRED'; end if;
  select * into p from desafia.players where id=pid;
  select * into r from desafia.rewards where id=p_reward and family_id=p.family_id and active;
  if r.id is null then raise exception 'INVALID_REWARD'; end if;
  if exists(select 1 from desafia.reward_requests where player_id=pid and reward_id=r.id and status='pending') then return; end if;
  update desafia.players set wallet=wallet-r.cost where id=pid and wallet>=r.cost;get diagnostics changed=row_count;
  if changed=0 then raise exception 'NOT_ENOUGH_STARS'; end if;
  insert into desafia.reward_requests(player_id,reward_id,cost) values(pid,r.id,r.cost);
  update desafia.devices set last_seen_at=now() where token_hash=desafia.token_hash(p_device_token);
end $$;

create or replace function desafia.update_my_pet(p_device_token text,p_pet_name text,p_look jsonb)
returns void language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare pid uuid;clean jsonb;lvl int;hat text;acc text;
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  pid:=desafia.device_player(p_device_token);if pid is null then raise exception 'NOT_PAIRED'; end if;
  select case
    when xp>=2700 then 10 when xp>=1350 then 7 when xp>=1000 then 6 when xp>=700 then 5 when xp>=450 then 4 when xp>=250 then 3 when xp>=100 then 2 else 1 end
    into lvl from desafia.players where id=pid;
  hat:=case p_look->>'hat' when 'bone' then case when lvl>=2 then 'bone' else 'none' end when 'festa' then case when lvl>=3 then 'festa' else 'none' end when 'gorro' then case when lvl>=4 then 'gorro' else 'none' end when 'coroa' then case when lvl>=6 then 'coroa' else 'none' end when 'mago' then case when lvl>=9 then 'mago' else 'none' end else 'none' end;
  acc:=case p_look->>'acc' when 'oculos' then case when lvl>=2 then 'oculos' else 'none' end when 'laco' then case when lvl>=3 then 'laco' else 'none' end when 'gravata' then case when lvl>=5 then 'gravata' else 'none' end else 'none' end;
  clean:=jsonb_build_object('color',case when p_look->>'color' in('rosa','azul','verde','amarelo','lilas') then p_look->>'color' else 'rosa' end,'hat',hat,'acc',acc);
  update desafia.players set pet_name=coalesce(nullif(left(trim(p_pet_name),12),''),pet_name),look=clean where id=pid;
  update desafia.devices set last_seen_at=now() where token_hash=desafia.token_hash(p_device_token);
end $$;

create or replace function desafia.kid_snapshot(p_device_token text)
returns jsonb language plpgsql security definer
set search_path=desafia,pg_catalog,extensions,pg_temp as $$
declare pid uuid;fid uuid;today date;ws date;
begin
  if auth.uid() is not null then raise exception 'FORBIDDEN'; end if;
  pid:=desafia.device_player(p_device_token);if pid is null then return null; end if;
  select family_id into fid from desafia.players where id=pid;today:=desafia.family_today(fid);ws:=desafia.family_week_start(fid);
  update desafia.devices set last_seen_at=now() where token_hash=desafia.token_hash(p_device_token);
  return jsonb_build_object(
    'family',(select jsonb_build_object('name',f.name) from desafia.families f where f.id=fid),
    'family_goal',jsonb_build_object('current',desafia.family_week_points(fid),'target',(select weekly_goal from desafia.families where id=fid)),
    'player',(select jsonb_build_object('id',p.id,'nickname',p.nickname,'avatar',p.avatar,'pet_name',p.pet_name,'look',p.look,'xp',p.xp,'wallet',p.wallet,'week_points',desafia.player_week_points(p.id,ws),'streak',desafia.player_streak(p.id,fid),'daily_bonus_day',(select max(day) from desafia.daily_completions where player_id=p.id and day=today)) from desafia.players p where p.id=pid),
    'missions',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'title',m.title,'icon',m.icon,'star_reward',m.star_reward,'xp_reward',m.xp_reward,'time_of_day',m.time_of_day,'status',coalesce(l.status,'todo')) order by m.sort,m.created_at) from desafia.missions m left join desafia.mission_logs l on l.mission_id=m.id and l.player_id=pid and l.day=today where m.family_id=fid and m.active and m.audience='child'),'[]'::jsonb),
    'rewards',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'title',r.title,'icon',r.icon,'cost',r.cost,'pending',exists(select 1 from desafia.reward_requests q where q.reward_id=r.id and q.player_id=pid and q.status='pending')) order by r.cost) from desafia.rewards r where r.family_id=fid and r.active),'[]'::jsonb),
    'recent_rewards',coalesce((select jsonb_agg(jsonb_build_object('id',q.id,'status',q.status,'title',r.title,'icon',r.icon,'decided_at',q.decided_at) order by q.decided_at) from desafia.reward_requests q join desafia.rewards r on r.id=q.reward_id where q.player_id=pid and q.status<>'pending' and q.decided_at>now()-interval '2 days'),'[]'::jsonb),
    'ranking',coalesce((select jsonb_agg(jsonb_build_object('nickname',p.nickname,'avatar',p.avatar,'kind',p.kind,'points',desafia.player_week_points(p.id,ws),'me',p.id=pid) order by desafia.player_week_points(p.id,ws) desc) from desafia.players p where p.family_id=fid),'[]'::jsonb),
    'challenges',coalesce((select jsonb_agg(jsonb_build_object('title',c.title,'target_days',c.target_days,'prize',c.prize,'icon',m.icon,'done',desafia.challenge_progress(c.id,pid),'ends_on',c.ends_on)) from desafia.challenges c join desafia.missions m on m.id=c.mission_id where c.family_id=fid and (c.player_id is null or c.player_id=pid) and today between c.starts_on and c.ends_on),'[]'::jsonb),
    'leagues',coalesce((select jsonb_agg(desafia.league_scores(lf.league_id,fid)) from desafia.league_families lf where lf.family_id=fid),'[]'::jsonb)
  );
end $$;

-- --------------------------------------------------------------------------
-- Permissões: NUNCA tocar em public. Somente desafia.*
-- --------------------------------------------------------------------------
revoke all on schema desafia from public;
grant usage on schema desafia to anon,authenticated,service_role;

revoke all on all tables in schema desafia from public,anon,authenticated;
revoke all on all sequences in schema desafia from public,anon,authenticated;
revoke execute on all functions in schema desafia from public,anon,authenticated;

grant all on all tables in schema desafia to service_role;
grant all on all sequences in schema desafia to service_role;
grant execute on all functions in schema desafia to service_role;

-- Responsáveis autenticados.
grant execute on function desafia.my_families() to authenticated;
grant execute on function desafia.create_family(text,text,text) to authenticated;
grant execute on function desafia.update_family(uuid,text,integer) to authenticated;
grant execute on function desafia.create_child(uuid,text,text) to authenticated;
grant execute on function desafia.update_player(uuid,uuid,text,text) to authenticated;
grant execute on function desafia.create_pairing_code(uuid) to authenticated;
grant execute on function desafia.parent_revoke_device(uuid,uuid) to authenticated;
grant execute on function desafia.create_parent_invite(uuid) to authenticated;
grant execute on function desafia.accept_parent_invite(text,text,text) to authenticated;
grant execute on function desafia.decide_mission(uuid,boolean) to authenticated;
grant execute on function desafia.parent_mark_done(uuid,uuid) to authenticated;
grant execute on function desafia.decide_reward(uuid,boolean) to authenticated;
grant execute on function desafia.parent_update_mission(uuid,uuid,text,text,integer,integer,text,boolean) to authenticated;
grant execute on function desafia.parent_create_mission(uuid,text,text,text,integer,integer,text) to authenticated;
grant execute on function desafia.parent_delete_mission(uuid,uuid) to authenticated;
grant execute on function desafia.parent_update_reward(uuid,uuid,text,text,integer,boolean) to authenticated;
grant execute on function desafia.parent_create_reward(uuid,text,text,integer) to authenticated;
grant execute on function desafia.parent_delete_reward(uuid,uuid) to authenticated;
grant execute on function desafia.parent_create_challenge(uuid,uuid,text,integer,text,uuid) to authenticated;
grant execute on function desafia.parent_delete_challenge(uuid,uuid) to authenticated;
grant execute on function desafia.create_league(uuid,text,text,text) to authenticated;
grant execute on function desafia.join_league(uuid,text,text,text) to authenticated;
grant execute on function desafia.parent_dashboard(uuid) to authenticated;

-- Aparelho infantil: papel anon + segredo do aparelho obrigatório.
grant execute on function desafia.pair_device(text,text,text) to anon;
grant execute on function desafia.unpair_device(text) to anon;
grant execute on function desafia.kid_snapshot(text) to anon;
grant execute on function desafia.mark_mission_done(text,uuid) to anon;
grant execute on function desafia.request_reward(text,uuid) to anon;
grant execute on function desafia.update_my_pet(text,text,jsonb) to anon;

-- Novos objetos futuros começam fechados por padrão para browsers.
alter default privileges for role postgres in schema desafia revoke all on tables from anon,authenticated;
alter default privileges for role postgres in schema desafia revoke all on sequences from anon,authenticated;
alter default privileges for role postgres in schema desafia revoke execute on functions from public,anon,authenticated;

commit;
