-- ============================================================================
-- DesafIA 0.5 — cobrança Plus isolada no schema desafia
-- Banco Inter no Web/PWA; entitlement independente do provedor para Android.
-- ============================================================================
-- Esta migration NÃO altera objetos de public. Ela apenas referencia auth.users.
-- O checkout PIX é criado/confirmado pela Edge Function desafia-billing usando
-- service_role; navegadores não recebem acesso direto às tabelas de cobrança.
-- ============================================================================

begin;

create table if not exists desafia.subscriptions (
  family_id            uuid primary key references desafia.families(id) on delete cascade,
  plan_code            text not null default 'plus_monthly' check (plan_code in ('plus_monthly')),
  provider             text not null default 'inter' check (provider in ('inter','google_play','manual')),
  status               text not null default 'active' check (status in ('active','past_due','canceled','expired')),
  current_period_start timestamptz not null,
  current_period_end   timestamptz not null,
  external_id          text,
  cancel_at_period_end boolean not null default false,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists desafia_subscriptions_status_idx
  on desafia.subscriptions(status,current_period_end);

create table if not exists desafia.billing_invoices (
  id              uuid primary key default gen_random_uuid(),
  family_id       uuid not null references desafia.families(id) on delete cascade,
  user_id         uuid not null references auth.users(id) on delete cascade,
  plan_code       text not null default 'plus_monthly' check (plan_code in ('plus_monthly')),
  provider        text not null default 'inter' check (provider in ('inter','google_play','manual')),
  channel         text not null default 'web' check (channel in ('web','play','admin')),
  amount_cents    integer not null check (amount_cents > 0),
  currency        text not null default 'BRL' check (currency='BRL'),
  status          text not null default 'pending' check (status in ('pending','paid','expired','canceled','failed')),
  txid            text unique,
  pix_code        text,
  qr_code_url     text,
  expires_at      timestamptz not null,
  paid_at         timestamptz,
  applied_at      timestamptz,
  period_start    timestamptz,
  period_end      timestamptz,
  metadata        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists desafia_billing_invoices_family_idx
  on desafia.billing_invoices(family_id,created_at desc);
create index if not exists desafia_billing_invoices_pending_idx
  on desafia.billing_invoices(family_id,status,expires_at)
  where status='pending';
create unique index if not exists desafia_billing_one_pending_per_family
  on desafia.billing_invoices(family_id)
  where status='pending';

-- Log genérico para um futuro Google Play Billing / User Choice Billing sem
-- exigir mudança de schema. O MVP Web/Inter não precisa preencher esta tabela.
create table if not exists desafia.billing_events (
  id                bigint generated by default as identity primary key,
  family_id         uuid references desafia.families(id) on delete cascade,
  invoice_id        uuid references desafia.billing_invoices(id) on delete set null,
  provider          text not null check (provider in ('inter','google_play','manual')),
  external_event_id text,
  event_type        text not null,
  payload           jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now(),
  unique(provider,external_event_id)
);
create index if not exists desafia_billing_events_family_idx
  on desafia.billing_events(family_id,created_at desc);

alter table desafia.subscriptions enable row level security;
alter table desafia.billing_invoices enable row level security;
alter table desafia.billing_events enable row level security;

-- Aplicação atômica/idempotente de um pagamento confirmado pelo servidor.
-- Cada PIX acrescenta 30 dias a partir de agora ou do vencimento atual,
-- o que estiver mais distante. Assim uma renovação antecipada não perde dias.
create or replace function desafia.apply_paid_invoice(
  p_invoice_id uuid,
  p_paid_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path=desafia,pg_catalog,extensions,pg_temp
as $$
declare
  inv desafia.billing_invoices;
  fam desafia.families;
  base_at timestamptz;
  start_at timestamptz;
  end_at timestamptz;
begin
  select * into inv
  from desafia.billing_invoices
  where id=p_invoice_id
  for update;

  if inv.id is null then
    raise exception 'INVOICE_NOT_FOUND';
  end if;

  if inv.applied_at is not null then
    return jsonb_build_object(
      'applied',false,
      'already_applied',true,
      'family_id',inv.family_id,
      'period_start',inv.period_start,
      'period_end',inv.period_end
    );
  end if;

  if inv.status not in ('pending','paid') then
    raise exception 'INVOICE_NOT_PAYABLE';
  end if;

  select * into fam
  from desafia.families
  where id=inv.family_id
  for update;

  if fam.id is null then
    raise exception 'FAMILY_NOT_FOUND';
  end if;

  base_at := greatest(coalesce(fam.plan_expires_at,now()),now());
  start_at := case when fam.plan_expires_at is not null and fam.plan_expires_at>now()
                   then fam.plan_expires_at else now() end;
  end_at := base_at + interval '30 days';

  update desafia.billing_invoices
     set status='paid',
         paid_at=coalesce(paid_at,p_paid_at,now()),
         applied_at=now(),
         period_start=start_at,
         period_end=end_at,
         updated_at=now()
   where id=inv.id;

  update desafia.families
     set plan='plus',
         plan_expires_at=end_at
   where id=inv.family_id;

  insert into desafia.subscriptions(
    family_id,plan_code,provider,status,current_period_start,current_period_end,
    external_id,cancel_at_period_end,created_at,updated_at
  ) values (
    inv.family_id,inv.plan_code,inv.provider,'active',start_at,end_at,
    inv.txid,false,now(),now()
  )
  on conflict (family_id) do update set
    plan_code=excluded.plan_code,
    provider=excluded.provider,
    status='active',
    current_period_start=excluded.current_period_start,
    current_period_end=excluded.current_period_end,
    external_id=excluded.external_id,
    cancel_at_period_end=false,
    updated_at=now();

  return jsonb_build_object(
    'applied',true,
    'family_id',inv.family_id,
    'period_start',start_at,
    'period_end',end_at,
    'provider',inv.provider
  );
end;
$$;

-- Objetos de billing ficam inacessíveis diretamente ao browser.
revoke all on desafia.subscriptions from public,anon,authenticated;
revoke all on desafia.billing_invoices from public,anon,authenticated;
revoke all on desafia.billing_events from public,anon,authenticated;
revoke all on sequence desafia.billing_events_id_seq from public,anon,authenticated;
revoke execute on function desafia.apply_paid_invoice(uuid,timestamptz) from public,anon,authenticated;

grant all on desafia.subscriptions to service_role;
grant all on desafia.billing_invoices to service_role;
grant all on desafia.billing_events to service_role;
grant usage,select on sequence desafia.billing_events_id_seq to service_role;
grant execute on function desafia.apply_paid_invoice(uuid,timestamptz) to service_role;

commit;
